title: no-brand
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

## setup link style
## deafult is 'date' /:categories/:year/:month/:day/:title:output_ext
## [reference] https://jekyllrb-ko.github.io/docs/permalinks/
permalink: date
baseurl: "" # the subpath of your site, e.g. /blog
url: "no-brand.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: no-brand #if your site has a twitter account, enter it here

# Author Settings
author: no-brand # add your name
author-img: profile.png # add your photo
about-author: hello world # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: no-brand # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: no-brand # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
## kramdown, modified markdown
markdown: kramdown
plugins:
  - jekyll-sitemap # generate sitemap.xml, may help to be searched
  - jekyll-paginate # pagination
  - jemoji

## pagenation
## /index.html, shows first n posts
## /page/2/index.html, shows next n+1 ~ 2n posts, and so on.
## [reference] https://jekyllrb-ko.github.io/docs/pagination/
paginate: 6 # max number of pages on one page
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
